# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LMY.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LYM(object):
    def setupUi(self, LYM):
        LYM.setObjectName("LYM")
        LYM.setWindowModality(QtCore.Qt.ApplicationModal)
        LYM.resize(800, 480)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(49, 51, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        LYM.setPalette(palette)
        LYM.setWindowOpacity(1.0)
        LYM.setLayoutDirection(QtCore.Qt.LeftToRight)
        LYM.setAutoFillBackground(True)
        self.timeLabel = QtWidgets.QLabel(LYM)
        self.timeLabel.setGeometry(QtCore.QRect(0, 10, 801, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.timeLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(81)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.dateLabel = QtWidgets.QLabel(LYM)
        self.dateLabel.setGeometry(QtCore.QRect(0, 90, 801, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.dateLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(18)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.nowIcon = QtWidgets.QLabel(LYM)
        self.nowIcon.setGeometry(QtCore.QRect(300, 130, 90, 90))
        self.nowIcon.setText("")
        self.nowIcon.setPixmap(QtGui.QPixmap("images/0.png"))
        self.nowIcon.setScaledContents(True)
        self.nowIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.nowIcon.setObjectName("nowIcon")
        self.nowTmp = QtWidgets.QLabel(LYM)
        self.nowTmp.setGeometry(QtCore.QRect(400, 140, 111, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nowTmp.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(30)
        self.nowTmp.setFont(font)
        self.nowTmp.setAlignment(QtCore.Qt.AlignCenter)
        self.nowTmp.setObjectName("nowTmp")
        self.nowText = QtWidgets.QLabel(LYM)
        self.nowText.setGeometry(QtCore.QRect(409, 180, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.nowText.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(23)
        self.nowText.setFont(font)
        self.nowText.setAlignment(QtCore.Qt.AlignCenter)
        self.nowText.setObjectName("nowText")
        self.label_5 = QtWidgets.QLabel(LYM)
        self.label_5.setGeometry(QtCore.QRect(150, 250, 34, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(LYM)
        self.label_6.setGeometry(QtCore.QRect(390, 250, 34, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(LYM)
        self.label_7.setGeometry(QtCore.QRect(640, 250, 34, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.day1Icon = QtWidgets.QLabel(LYM)
        self.day1Icon.setGeometry(QtCore.QRect(130, 290, 70, 70))
        self.day1Icon.setText("")
        self.day1Icon.setPixmap(QtGui.QPixmap("images/4.png"))
        self.day1Icon.setScaledContents(True)
        self.day1Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.day1Icon.setObjectName("day1Icon")
        self.day2Icon = QtWidgets.QLabel(LYM)
        self.day2Icon.setGeometry(QtCore.QRect(370, 290, 70, 70))
        self.day2Icon.setText("")
        self.day2Icon.setPixmap(QtGui.QPixmap("images/14.png"))
        self.day2Icon.setScaledContents(True)
        self.day2Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.day2Icon.setObjectName("day2Icon")
        self.day3Icon = QtWidgets.QLabel(LYM)
        self.day3Icon.setGeometry(QtCore.QRect(620, 290, 70, 70))
        self.day3Icon.setText("")
        self.day3Icon.setPixmap(QtGui.QPixmap("images/19.png"))
        self.day3Icon.setScaledContents(True)
        self.day3Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.day3Icon.setObjectName("day3Icon")
        self.day3Text = QtWidgets.QLabel(LYM)
        self.day3Text.setGeometry(QtCore.QRect(620, 370, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day3Text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day3Text.setFont(font)
        self.day3Text.setTextFormat(QtCore.Qt.RichText)
        self.day3Text.setAlignment(QtCore.Qt.AlignCenter)
        self.day3Text.setObjectName("day3Text")
        self.day1Text = QtWidgets.QLabel(LYM)
        self.day1Text.setGeometry(QtCore.QRect(130, 370, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day1Text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day1Text.setFont(font)
        self.day1Text.setTextFormat(QtCore.Qt.RichText)
        self.day1Text.setAlignment(QtCore.Qt.AlignCenter)
        self.day1Text.setObjectName("day1Text")
        self.day2Text = QtWidgets.QLabel(LYM)
        self.day2Text.setGeometry(QtCore.QRect(370, 370, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day2Text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day2Text.setFont(font)
        self.day2Text.setTextFormat(QtCore.Qt.RichText)
        self.day2Text.setAlignment(QtCore.Qt.AlignCenter)
        self.day2Text.setObjectName("day2Text")
        self.day3Tmp = QtWidgets.QLabel(LYM)
        self.day3Tmp.setGeometry(QtCore.QRect(620, 400, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day3Tmp.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day3Tmp.setFont(font)
        self.day3Tmp.setTextFormat(QtCore.Qt.RichText)
        self.day3Tmp.setAlignment(QtCore.Qt.AlignCenter)
        self.day3Tmp.setObjectName("day3Tmp")
        self.day2Tmp = QtWidgets.QLabel(LYM)
        self.day2Tmp.setGeometry(QtCore.QRect(370, 400, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day2Tmp.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day2Tmp.setFont(font)
        self.day2Tmp.setTextFormat(QtCore.Qt.RichText)
        self.day2Tmp.setAlignment(QtCore.Qt.AlignCenter)
        self.day2Tmp.setObjectName("day2Tmp")
        self.day1Tmp = QtWidgets.QLabel(LYM)
        self.day1Tmp.setGeometry(QtCore.QRect(130, 400, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.day1Tmp.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.day1Tmp.setFont(font)
        self.day1Tmp.setTextFormat(QtCore.Qt.RichText)
        self.day1Tmp.setAlignment(QtCore.Qt.AlignCenter)
        self.day1Tmp.setObjectName("day1Tmp")
        self.icon = QtWidgets.QLabel(LYM)
        self.icon.setGeometry(QtCore.QRect(0, 730, 70, 70))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("images/mi.png"))
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.helloMiya = QtWidgets.QLabel(LYM)
        self.helloMiya.setGeometry(QtCore.QRect(70, 760, 401, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.helloMiya.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Wawati SC")
        font.setPointSize(17)
        self.helloMiya.setFont(font)
        self.helloMiya.setTextFormat(QtCore.Qt.RichText)
        self.helloMiya.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.helloMiya.setObjectName("helloMiya")

        self.retranslateUi(LYM)
        QtCore.QMetaObject.connectSlotsByName(LYM)

    def retranslateUi(self, LYM):
        _translate = QtCore.QCoreApplication.translate
        LYM.setWindowTitle(_translate("LYM", "LMY"))
        self.timeLabel.setText(_translate("LYM", "14:34"))
        self.dateLabel.setText(_translate("LYM", "6月20日 星期二"))
        self.nowTmp.setText(_translate("LYM", "30°C"))
        self.nowText.setText(_translate("LYM", "晴"))
        self.label_5.setText(_translate("LYM", "今天"))
        self.label_6.setText(_translate("LYM", "明天"))
        self.label_7.setText(_translate("LYM", "后天"))
        self.day3Text.setText(_translate("LYM", "阴有雨"))
        self.day1Text.setText(_translate("LYM", "多云"))
        self.day2Text.setText(_translate("LYM", "晴"))
        self.day3Tmp.setText(_translate("LYM", "30°/34°"))
        self.day2Tmp.setText(_translate("LYM", "20°/30°"))
        self.day1Tmp.setText(_translate("LYM", "26°/34°"))
        self.helloMiya.setText(_translate("LYM", "多云"))

